version: "3.5"
services:
    sleck-fe:
        build: ./
        networks:
            - sleck-infra
    sleck-nginx:
        build: ./nginx
        ports:
            - 80:80
            - 443:443
        networks:
            - sleck-infra
networks:
    sleck-infra:
        external:
            name: slecknet
