import { createAsyncThunk, createSlice, AsyncThunkAction, AnyAction } from "@reduxjs/toolkit";
import { apiRequest } from "@/services/apiRequest";
import { RootState } from "../../store";

// here we are typing the types for the state
type InitialState = {
    data: RoomObj[];
    loading: boolean;
    error: boolean;
    errorMsg: string;
};

export type RoomObj = {
    uid: number;
    room_logo?: string;
    room_name?: string;
    room_description?: string;
    created_at?: string;
    updated_at?: string;
};

const initialState: InitialState = {
    data: [],
    loading: false,
    error: false,
    errorMsg: "",
};

// This action is what we will call using the dispatch in order to trigger the API call.
export const getAllRooms = createAsyncThunk(
    "rooms/getAll",
    async (channel_uid: any, { rejectWithValue }) => {
        const response = await apiRequest({
            method: "POST",
            url: "channels/getRooms",
            data: { channel_uid },
        });
        if (!response.data.status) {
            return rejectWithValue(response.data.data);
        }
        return response.data.data;
    }
);

export const roomsSlice = createSlice({
    name: "rooms",
    initialState,
    reducers: {
        // leave this empty here
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere, including actions generated by createAsyncThunk or in other slices.
    // Since this is an API call we have 3 possible outcomes: pending, fulfilled and rejected. We have made allocations for all 3 outcomes.
    // Doing this is good practice as we can tap into the status of the API call and give our users an idea of what's happening in the background.
    extraReducers: (builder) => {
        builder
            .addCase(getAllRooms.pending, (state) => {
                state.loading = true;
            })
            .addCase(getAllRooms.fulfilled, (state, { payload }) => {
                // When the API call is successful and we get some data,the data becomes the `fulfilled` action payload
                state.loading = false;
                state.data = payload;
            })
            .addCase(getAllRooms.rejected, (state) => {
                state.loading = false;
                state.error = true;
            });
    },
});

export const selectRooms = (state: RootState) => state.rooms;

export default roomsSlice.reducer;
