import { createSlice } from "@reduxjs/toolkit";
import { RootState } from "../../store";
import { ChannelsObj } from "../channels/getAll";
import { RoomObj } from "../rooms/getAll";

type InitialState = {
    currentChannel: ChannelsObj;
    currentRoom: RoomObj;
    isSendMessage: boolean;
};

const initialState: InitialState = {
    currentChannel: { uid: 0 },
    currentRoom: { uid: 0 },
    isSendMessage: false,
};

export const globalsSlice = createSlice({
    name: "globals",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        setCurrentChannel: (state, action) => {
            state.currentChannel = action.payload;
        },
        setCurrentRoom: (state, action) => {
            state.currentRoom = action.payload;
        },
        setIsSendMessage: (state, action) => {
            state.isSendMessage = action.payload;
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {},
});

export const { setCurrentChannel, setCurrentRoom, setIsSendMessage } = globalsSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.globals.value)`
export const selectGlobals = (state: RootState) => state.globals;

export default globalsSlice.reducer;
